name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build archive
      run: |
        xcodebuild archive \
        -project iOS-SmartWebView.xcodeproj \
        -scheme iOS-SmartWebView \
        -configuration Release \
        -archivePath build/app.xcarchive \
        CODE_SIGNING_ALLOWED=NO

    - name: Make IPA
      run: |
        mkdir -p Payload
        cp -R build/app.xcarchive/Products/Applications/*.app Payload/
        zip -r SmartWebView-UNSIGNED.ipa Payload

    - uses: actions/upload-artifact@v4
      with:
        name: SmartWebView-UNSIGNED
        path: SmartWebView-UNSIGNED.ipa
