name: Build Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build unsigned archive
      run: |
        xcodebuild clean archive \
        -project unsigned_browser.xcodeproj \   # <- proje dosya adı repo ile aynı
        -scheme unsigned_browser \              # <- scheme adı
        -configuration Release \
        -archivePath build/unsigned_browser.xcarchive \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGN_IDENTITY=""

    - name: Export unsigned IPA
      run: |
        mkdir -p build/ipa/Payload
        cp -R build/unsigned_browser.xcarchive/Products/Applications/*.app build/ipa/Payload/
        cd build/ipa
        zip -r unsigned_browser-UNSIGNED.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: unsigned_browser-UNSIGNED
        path: build/ipa/*.ipa
